# Day 2: NumPy Array Creation

**NumPy**  is a popular Python library used for scientific computing, particularly for working with arrays. NumPy arrays are similar to Python lists, but they offer more efficient and convenient ways to perform mathematical operations on large datasets.

There are several ways to create a NumPy array. Below are different methods for creating arrays in NumPy:

1. Creating an Array from a List or Tuple
You can create a NumPy array directly from a Python list or tuple using the np.array() function. This is the simplest way to create an array.

**Example 1: Creating an array from a list**



In [3]:
import numpy as np

my_list = [1, 2, 3, 4, 5]
a = np.array(my_list)
print(a)


[1 2 3 4 5]


In this example, a Python list my_list containing integers is converted into a NumPy array using np.array(). The array a will contain the same elements as the list.

**Example 2: Creating an array from a tuple**

In [6]:
import numpy as np

my_tuple = (1, 2, 3, 4, 5)
a = np.array(my_tuple)
print(a)


[1 2 3 4 5]


This example is similar to the previous one, but it uses a tuple instead of a list. NumPy treats both lists and tuples similarly when creating arrays.

**2. Creating an Array of Zeros or Ones**

NumPy provides functions to create arrays filled with zeros or ones. This can be useful when initializing arrays for certain computations.

**Example 1: Array of zeros**

In [9]:
import numpy as np

a = np.zeros(5)
print(a)


[0. 0. 0. 0. 0.]


This code creates a one-dimensional array of zeros with a length of 5 using the np.zeros() function.


**Example 2: Two-dimensional array of zeros**

In [12]:
import numpy as np

a = np.zeros((3, 3))
print(a)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


Here, a 3x3 array filled with zeros is created.


**Example 3: Array of ones**

In [15]:
import numpy as np

a = np.ones(5)
print(a)


[1. 1. 1. 1. 1.]


This example creates a one-dimensional array of ones with a length of 5 using the np.ones() function.

    
**Example 4: Two-dimensional array of ones**

In [18]:
import numpy as np

a = np.ones((2, 2))
print(a)


[[1. 1.]
 [1. 1.]]


A 2x2 array filled with ones is created in this example.


    
**3. Creating an Array with a Range of Values**
You can use np.arange() to create an array with a sequence of values. This function is similar to Python’s built-in range() function, but it returns a NumPy array.

**Example:**

In [24]:
import numpy as np

a = np.arange(0, 10, 2)
print(a)


[0 2 4 6 8]


This creates an array with values starting at 0, ending before 10, and incrementing by 2.


    
**4. Creating an Array of Random Values**
NumPy’s np.random.rand() function can be used to create arrays with random values. The shape of the array is specified as arguments.

**Example:**

In [27]:
import numpy as np

a = np.random.rand(2, 4)
print(a)


[[0.60244921 0.74817799 0.99735246 0.10769351]
 [0.28516039 0.79433792 0.41433112 0.47703797]]


This code creates a 2x4 array with random values between 0 and 1.


    
**5. Creating an Array of Evenly Spaced Values**
The np.linspace() function generates arrays of evenly spaced values over a specified interval.

**Example:**

In [32]:
import numpy as np

a = np.linspace(0, 1, 11)
print(a)


[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]


This generates an array of 11 evenly spaced values between 0 and 1, inclusive.



**Summary**
These methods illustrate different ways to create arrays in NumPy. Arrays can be initialized with specific values, zeros, ones, random values, or even a range of values. 

These arrays are fundamental to handling large datasets and performing complex mathematical computations efficiently in scientific computing.