# **Day-03 NumPy Array Indexing**

**Array indexing** refers to the way in which elements of an array are selected and manipulated. In NumPy, arrays can be indexed using various methods, such as slicing, fancy indexing, and boolean indexing.


**Slicing** involves selecting a range of elements from an array.
**Fancy indexing** allows you to select elements using a list or array of indices.
**Boolean indexing** involves selecting elements based on a condition or logical expression.
NumPy array indexing can be used for a wide range of tasks, such as filtering data, selecting specific elements from an array, and performing mathematical operations on subsets of an array. With its efficient array indexing capabilities, NumPy is an essential tool for many scientific and data analysis applications in Python.

# Examples of NumPy Array Indexing
**1. Indexing a One-Dimensional Array**


Example:

In [5]:
import numpy as np
a = np.array([1, 2, 3, 4])
print("output:", a[2])


output: 3


**Explanation:**

The code creates a NumPy array a with the values [1, 2, 3, 4]. It then uses indexing to select the element at index 2 of the array, which is the value 3. When executed, it prints 3 to the console.

**2. Indexing a Two-Dimensional Array**

Example 01:

In [9]:
import numpy as np
a = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print("original input array:", a)
print("output index:", a[0, 1])


original input array: [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
output index: 2


**Explanation:**
This code creates a 2-dimensional NumPy array a with values [[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]. The indexing operation a[0, 1] selects the element at row 0 and column 1 of the array, which is the value 2.

    
Example 02:

In [12]:
a = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15]])
print("original input array:", a)
print("output index:", a[0, 1])


original input array: [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
output index: 2


**Explanation:**
The code creates a 2-dimensional array a with dimensions 3x5 and values ranging from 1 to 15. The output shows the element at row 0 and column 1, which is 2.

 **3. Indexing a Three-Dimensional Array**

Example:

In [16]:
a = np.array([[[0, 1, 2], [3, 4, 5]], [[0, 1, 2], [3, 4, 5]]])
print("original input array:", a)
print("output index:", a[0, 1])


original input array: [[[0 1 2]
  [3 4 5]]

 [[0 1 2]
  [3 4 5]]]
output index: [3 4 5]


**Explanation:**
This code creates a 3-dimensional NumPy array a with shape (2, 2, 3). The indexing operation a[0, 1] selects the array [3, 4, 5] from the first 2x3 array.



**4.  Negative Indexing in One-Dimensional Array**

Example:

In [22]:
a = np.array([1, 2, 3, 4])
print("output index:", a[-2])


output index: 3


**Explanation:**
The code creates a NumPy array a with values [1, 2, 3, 4]. Using negative indexing, a[-2] selects the second-to-last element, which is 3.



**5. Negative Indexing in Two-Dimensional Array**
    
Example 01:

In [25]:
a = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print("output index:", a[1, -4])


output index: 7


Negative Indexing in Three-Dimensional Array
Example:

In [30]:
a = np.array([[[0, 1, 2], [3, 4, 5]], [[0, 1, 2], [3, 4, 5]]])
print("original input array:", a)
print("output index:", a[0, -1])


original input array: [[[0 1 2]
  [3 4 5]]

 [[0 1 2]
  [3 4 5]]]
output index: [3 4 5]


**Summary**

NumPy's powerful indexing methods enable efficient and convenient manipulation of array data, making it a valuable tool for scientific computing and data analysis in Python. Whether working with one-dimensional, two-dimensional, or multi-dimensional arrays, NumPy provides flexible and intuitive ways to access and modify array elements.