# Day 1:  Creating Arrays in NumPy
**NumPy Library**

This code creates a NumPy array called a with the values 0.0, 1.5, and 2.0, and with the data type np.float64, which specifies that the array should contain 64-bit floating-point numbers.

The first line imports the NumPy library and assigns the name np to it, which is a common convention.

The second line creates a NumPy array called a with the values 0.0, 1.5, and 2.0, and with the data type np.float64.

The third line prints the contents of the a; array to the console.

In [2]:
import numpy as np

arr = np.array([0, 1, 2, 3, 4])


**Example 1: Creating a One-Dimensional Array**

In [4]:
import numpy as np

a = np.array([0, 1, 2, 3, 4])
print("Array:", a)
print("Dimensions:", np.ndim(a))
print("Shape:", np.shape(a))


Array: [0 1 2 3 4]
Dimensions: 1
Shape: (5,)


**Creating a Two-Dimensional Array**
You can create a two-dimensional array by passing a list of lists to the numpy.array() function. For example, to create a 2x3 array of integers, you would write:

In [6]:
import numpy as np

arr = np.array([[0, 1, 2], [3, 4, 5]])


**Example 2: Creating a Two-Dimensional Array**

In [8]:
import numpy as np

a = np.array([[0, 1, 2], [3, 4, 5]])
print("Array:", a)
print("Dimensions:", np.ndim(a))
print("Shape:", np.shape(a))


Array: [[0 1 2]
 [3 4 5]]
Dimensions: 2
Shape: (2, 3)


**Creating Higher-Dimensional Arrays**

Higher-dimensional arrays are arrays with more than one dimension, used to represent complex data structures like images, audio signals, and scientific data. These can be thought of as lists of lists, where each element in the list can itself be a list or an array.

For example:

A two-dimensional array can be visualized as a matrix (rows and columns).
A three-dimensional array can be visualized as a cube, with layers stacked on top of each other.
You can create higher-dimensional arrays using the numpy.array() function, specifying the desired shape and data type if needed.

Creating Arrays with Specific Data Types
NumPy allows you to specify the data type of the elements in an array using the dtype parameter. This feature is useful when you need to ensure that the array holds specific types of data, such as integers, floating-point numbers, or even complex numbers.

In [10]:
import numpy as np

arr = np.array([0.0, 1.0, 2.0], dtype=np.float64)


**Example 3: Creating a Three-Dimensional Array**

In [12]:
import numpy as np

a = np.array([[[0, 1, 2], [3, 4, 5]], [[0, 1, 2], [3, 4, 5]]])
print("Array:", a)
print("Dimensions:", np.ndim(a))
print("Shape:", np.shape(a))


Array: [[[0 1 2]
  [3 4 5]]

 [[0 1 2]
  [3 4 5]]]
Dimensions: 3
Shape: (2, 2, 3)


**Example 4: Creating a Higher-Dimensional Array**


In [14]:
import numpy as np

a = np.array([1, 2, 3, 4, 5, 6, 7, 8], ndmin=5)
print(a)


[[[[[1 2 3 4 5 6 7 8]]]]]


This code creates a five-dimensional array, where additional dimensions have a size of 1 to meet the specified minimum of five dimensions.

**Example 5: Creating an Array with a Specific Data Type**


In [17]:
import numpy as np

a = np.array([0.0, 1.5, 2.0], dtype=np.float64)
print(a)


[0.  1.5 2. ]


This example creates an array of 64-bit floating-point numbers.

These notes cover the basics of creating arrays in NumPy, including various dimensions and data types, which are fundamental when working with scientific data and computations.