# **Numpy Array Reshaping And Searching**

# 1. What is Reshape in NumPy

The reshape function in NumPy allows you to give a new shape to an array without changing its data. It returns a new array with the same data but a different shape.

This functionality is particularly useful when working with different dimensions of data, like transforming a 1D array into a 2D array or reshaping a 3D array into a 2D array.

**NumPy** is a popular Python library used for numerical computing. It provides powerful tools for array manipulation, including reshaping an array. Reshaping is the process of changing the shape or dimensions of an existing array without changing the data within it.

Syntax for Reshaping a NumPy Array

***new_arr = arr.reshape(new_shape)***


**arr:** The original NumPy array to be reshaped.

**new_shape:** A tuple indicating the new shape of the array.

**Example:** Reshaping a NumPy Array
Suppose we have a NumPy array arr with shape (3, 4):

In [12]:
import numpy as np

arr = np.array([[1, 2, 3, 4], 
                [5, 6, 7, 8], 
                [9, 10, 11, 12]])

new_arr = arr.reshape((4, 3))

print("Original array:\n", arr)
print("Reshaped array:\n", new_arr)


Original array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Reshaped array:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


**Explanation:**

The reshape() method is used to change the shape of arr from (3, 4) to (4, 3).
    
    The total number of elements remains the same (12 elements).

# Key Points of Reshaping 
**Compatibility of Shapes:** When reshaping an array, the total number of elements must remain the same. For example, a (3, 4) array with 12 elements can be reshaped into (4, 3) because both shapes contain 12 elements.

**New Shape as Tuple:** The new shape is specified as a tuple. For example, (4, 3) means 4 rows and 3 columns.

**In-Place or New Array:** The reshape() method returns a new array with the new shape, and it does not modify the original array.

   # **Additional Methods for Reshaping Arrays**
**flatten():** Returns a 1D copy of the array, collapsing all dimensions.

**ravel():** Returns a flattened 1D array, similar to flatten(), but may not create a copy if possible.

**transpose():** Transposes the array, swapping rows with columns.

**1. Reshaping One-Dimensional Arrays**
    
Example 1: Reshaping to 2D Array

In [19]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(4, 3)

print("Output Reshape:\n", newarr)


Output Reshape:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


**Explanation:**

The one-dimensional array arr is reshaped into a two-dimensional array with 4 rows and 3 columns.

**Example 2: Reshaping to 3D Array**


In [27]:
import numpy as np

a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
b = a.reshape(2, 3, 2)

print("Output Reshape:\n", b)
print("\nNumber of dimensions:", np.ndim(b))


Output Reshape:
 [[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]

Number of dimensions: 3


**Explanation:**

The one-dimensional array a is reshaped into a three-dimensional array with 2 layers, 3 rows, and 2 columns. The total number of elements (12) remains the same.

**2. Reshaping Two-Dimensional Arrays**


**Example 1: Changing Number of Rows and Columns**


In [40]:
import numpy as np

a = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]])

b = a.reshape(6, 2)

print("Output:\n", b)


Output:
 [[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]


**Explanation:**

The original 2D array a with shape (3, 4) is reshaped into a (6, 2) array, where the total number of elements (12) is preserved.


**Example 2: Reshaping to 3D Array**


In [45]:
a = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12],
              [13, 14, 15, 16],
              [17, 18, 19, 20],
              [21, 22, 23, 24]])

b = a.reshape(2, 3, 4)

print("Original array:\n", a)
print("\nReshaped array:\n", b)


Original array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]

Reshaped array:
 [[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


**Explanation:**

A 2D array a is reshaped into a 3D array b with 2 layers, 3 rows, and 4 columns, ensuring the total number of elements (24) remains unchanged.


**3. Reshaping Three-Dimensional Arrays**

**Example 1: Reducing Dimensions**

In [50]:
import numpy as np

a = np.array([[[1, 2, 3, 4],
               [5, 6, 7, 8],
               [9, 10, 11, 12]],
              [[13, 14, 15, 16],
               [17, 18, 19, 20],
               [21, 22, 23, 24]]])

b = a.reshape(6, 4)

print("Original Array:\n", a)
print("\nReshaped Array:\n", b)


Original Array:
 [[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]

Reshaped Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]


**Explanation:**

The 3D array a is reshaped into a 2D array b with 6 rows and 4 columns, preserving the total number of elements (24).


**Example 2: Flattening to a Single Row**

In [56]:
a = np.array([[[1, 2, 3, 4],
               [5, 6, 7, 8],
               [9, 10, 11, 12]],
              [[13, 14, 15, 16],
               [17, 18, 19, 20],
               [21, 22, 23, 24]]])

b = a.reshape(1, 24)

print("Original Array:\n", a)
print("\nReshaped Array:\n", b)


Original Array:
 [[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]

Reshaped Array:
 [[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]]


**Explanation:**

The 3D array a is reshaped into a 2D array b with 1 row and 24 columns, effectively flattening the array into a single row.


**Conclusion**

Reshaping is a flexible and powerful way to manipulate arrays for data processing and analysis.

    The shape of the new array must have the same total number of elements as the original array.

    Reshaping can help in organizing data into different dimensions for various computational needs.

# **2. NumPy Searching Arrays**

Searching for specific elements or values in an array is a common operation in data analysis and manipulation. NumPy provides several functions for searching arrays, which allow users to locate elements based on specific criteria or conditions. This introduction will focus on the following functions:

np.where(): Finds indices of elements that satisfy a given condition.
    
np.searchsorted(): Finds indices where elements should be inserted to maintain order.

np.argmin(), np.argmax(), and np.nonzero(): Find indices of minimum, maximum, and non-zero elements.
# 1. numpy.where() Function
The **numpy.where()** function is used to find the indices of elements in an array that satisfy a specific condition. This function can be very useful for filtering arrays based on conditions or extracting specific elements.


Example 01: Find the indices where the value is 4


In [12]:
import numpy as np

# Creating a NumPy array
arr = np.array([1, 2, 3, 4, 5, 4, 4])

# Using np.where() to find indices where the array element equals 4
x = np.where(arr == 4)

# Output the result
print(x)


(array([3, 5, 6], dtype=int64),)


**Explanation:**

import numpy as np: Imports the NumPy library and aliases it as np.

arr = np.array([1, 2, 3, 4, 5, 4, 4]): Creates a NumPy array with specific values.

    x = np.where(arr == 4): Uses the np.where() function to find the indices where the element equals 4.

print(x): Prints the indices where the condition is met. Expected output: (array([3, 5, 6]),), indicating the positions of value 4.


**Example 02: Find the indices where the values are even**

In [18]:
import numpy as np

# Creating a NumPy array
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

# Using np.where() to find indices where elements are even
x = np.where(arr % 2 == 0)

# Output the result
print(x)


(array([1, 3, 5, 7], dtype=int64),)


**Explanation:**

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8]): Creates an array of integers.

    x = np.where(arr % 2 == 0): Checks for even numbers (remainder of division by 2 is zero).

print(x): Prints indices of even numbers. Expected output: (array([1, 3, 5, 7]),).

**Example 03: Find the indices where the values are odd**

In [28]:
import numpy as np

# Creating a NumPy array
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

# Using np.where() to find indices where elements are odd
x = np.where(arr % 2 == 1)

# Output the result
print(x)


(array([0, 2, 4, 6], dtype=int64),)


**Explanation:**

x = np.where(arr % 2 == 1): Finds indices of odd numbers (remainder of division by 2 is one).

print(x): Prints indices of odd numbers. Expected output: (array([0, 2, 4, 6]),).

**Example 04: Find the indices of all elements in a 2-dimensional array where the value is 3**

In [34]:
import numpy as np

# Creating a 2D NumPy array
arr = np.array([[1, 2, 3], [3, 5, 6]])

# Display the original array
print("Original array:", arr)
print()

# Using np.where() to find indices where elements equal 3
idx = np.where(arr == 3)

# Output the result
print(idx)


Original array: [[1 2 3]
 [3 5 6]]

(array([0, 1], dtype=int64), array([2, 0], dtype=int64))


**Explanation:**

arr = np.array([[1, 2, 3], [3, 5, 6]]): Creates a 2D array.
    
print("Original array:", arr): Prints the original array.

idx = np.where(arr == 3): Finds indices of elements equal to 3.

    print(idx): Prints indices of the value 3. Expected output: (array([0, 1]), array([2, 0])), indicating positions (0, 2) and (1, 0).


**Example 05: Find the indices of all elements in a 2-dimensional array where the values are even**

In [44]:
import numpy as np

# Creating a 2D NumPy array
arr = np.array([[1, 2, 3], [3, 5, 6]])

# Using np.where() to find indices where elements are even
idx = np.where(arr % 2 == 0)

# Output the result
print(idx)


(array([0, 1], dtype=int64), array([1, 2], dtype=int64))


**Explanation:**

idx = np.where(arr % 2 == 0): Finds indices of even elements.

    print(idx): Prints indices of even elements. Expected output: (array([0, 1]), array([1, 2])), indicating positions (0, 1) and (1, 2).


**Example 06: Find the indices of all elements in a 2-dimensional array that are greater than a given value**

In [48]:
import numpy as np

# Creating a 2D NumPy array
arr = np.array([[1, 2, 3], [4, 5, 6]])

# Display the original array
print("Original array:", arr)
print()

# Using np.where() to find indices where elements are greater than 3
idx = np.where(arr > 3)

# Output the result
print(idx)


Original array: [[1 2 3]
 [4 5 6]]

(array([1, 1, 1], dtype=int64), array([0, 1, 2], dtype=int64))


**Explanation:**

arr = np.array([[1, 2, 3], [4, 5, 6]]): Creates a 2D array.

    idx = np.where(arr > 3): Finds indices of elements greater than 3.

    print(idx): Prints indices of elements greater than 3. Expected output: (array([1, 1, 1]), array([0, 1, 2])), indicating positions (1, 0), (1, 1), and (1, 2).


**Example 07: Find the indices of all elements in a 2-dimensional array that are less than a given value**

In [52]:
import numpy as np

# Creating a 2D NumPy array
arr = np.array([[1, 2, 3], [4, 5, 6]])

# Display the original array
print("Original array:", arr)
print()

# Using np.where() to find indices where elements are less than 3
idx = np.where(arr < 3)

# Output the result
print(idx)


Original array: [[1 2 3]
 [4 5 6]]

(array([0, 0], dtype=int64), array([0, 1], dtype=int64))


**Explanation:**

idx = np.where(arr < 3): Finds indices of elements less than 3.

    print(idx): Prints indices of elements less than 3. Expected output: (array([0, 0]), array([0, 1])), indicating positions (0, 0) and (0, 1).


# 2.  numpy.searchsorted()
The **numpy.searchsorted()** function is used to find indices where elements should be inserted to maintain order in a sorted array. This is particularly useful for finding the insertion point of a new element.



# 3. np.argmin(), np.argmax(), and np.nonzero()
These functions return indices of minimum, maximum, and non-zero elements in an array. They are used for finding specific elements in an array, which is useful in optimization and filtering tasks.



These are the basic searching functions in NumPy that help in finding and manipulating specific elements based on conditions. Let me know if you would like to see examples or explanations for numpy.searchsorted(), np.argmin(), np.argmax(), and np.nonzero() functions as well!