# Statistical Functions in NumPy


NumPy is a powerful Python library that provides numerous statistical functions to analyze and describe data efficiently. Below are detailed explanations of some of the most commonly used statistical functions:

**1. numpy.mean()**
The mean() function calculates the arithmetic mean of the data along a specified axis.

**Syntax:**
*numpy.mean(arr, axis=None)*


**Examples:**
  

**1D Array:**

In [7]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(np.mean(arr))  # Output: 3.0


3.0


**2D Array (Column-wise):**

In [11]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(np.mean(a, axis=0))  # Output: [4. 5. 6.]


[4. 5. 6.]


**2D Array (Row-wise):**

In [21]:
print(np.mean(a, axis=1))  # Output: [2. 5. 8.]


[2. 5. 8.]


**Weighted Mean:**

In [24]:
weights = np.array([1, 2, 3, 4, 5])
print(np.average(arr, weights=weights))  # Output: 3.6666666666666665


3.6666666666666665


**2. numpy.median()**
The median() function calculates the median, the middle value in the sorted data.

**Syntax:** 
*numpy.median(arr, axis=None)*



**Examples:**

**1D Array:**

In [32]:
arr = np.array([3, 1, 4, 2, 5])
print(np.median(arr))  # Output: 3.0


3.0


**2D Array (Column-wise):**

In [35]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
print(np.median(arr, axis=0))  # Output: [5.5 6.5 7.5]


[5.5 6.5 7.5]


**2D Array (Row-wise):**

In [49]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])

print(np.median(arr, axis=1))  # Output: [ 2.  5.  8. 11.]


[ 2.  5.  8. 11.]


**3. numpy.std()**
The std() function calculates the standard deviation, which measures the dispersion of the data.

**Syntax:**
*numpy.std(arr, axis=None)*


**Examples:**

**1D Array:**

In [53]:
arr = np.array([1, 2, 3, 4, 5])
print(np.std(arr))  # Output: 1.4142135623730951


1.4142135623730951


**2D Array:**

In [56]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(np.std(arr))  # Output: 1.707825127659933


1.707825127659933


**4. numpy.var()**

The var() function calculates the variance of the array.

**Syntax:**
*numpy.var(arr, axis=None)*


**Example:**


In [60]:
arr = np.array([1, 2, 3, 4, 5])
print(np.var(arr))  # Output: 2.0


2.0


**5. numpy.percentile()**
The percentile() function computes the q-th percentile of the data.

**Syntax:**
*numpy.percentile(arr, q)*


**Example:**

In [ ]:
arr = np.array([1, 2, 3, 4, 5])
print(np.percentile(arr, 50))  # Output: 3.0


**6. numpy.histogram()**
The histogram() function computes the frequency distribution of data.

**Syntax:**
*numpy.histogram(arr, bins)*


**Example:**

In [75]:
arr = np.array([1, 2, 2, 3, 3, 3, 4, 4, 5])
hist, bins = np.histogram(arr, bins=5)
print(hist)  # Output: [1 2 3 2 1]


[1 2 3 2 1]


**7. numpy.corrcoef()**
The corrcoef() function computes the Pearson correlation coefficient.

**Syntax:**
*numpy.corrcoef(x, y)*



**Example:**

In [79]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
print(np.corrcoef(x, y))  # Output: [[1. 1.] [1. 1.]]


[[1. 1.]
 [1. 1.]]


**8. numpy.ptp()**
The ptp() function returns the range (peak-to-peak) of values.

**Syntax:**
*numpy.ptp(arr)*


**Example:**

In [85]:
arr = np.array([1, 2, 3, 4, 5])
print(np.ptp(arr))  # Output: 4


4


**9. numpy.average()**
The average() function calculates the weighted average.

**Syntax:** 
*numpy.average(arr, weights=None)*


**Example:**

In [94]:
arr = np.array([1, 2, 3, 4, 5])
weights = np.array([1, 2, 3, 4, 5])
print(np.average(arr, weights=weights))  # Output: 3.6666666666666665


3.6666666666666665


**Conclusion:**
  
NumPy's statistical functions provide efficient and easy-to-use tools for analyzing data. Whether calculating the mean, median, or standard deviation, these functions handle large datasets and multi-dimensional arrays with ease.

This summary outlines essential NumPy statistical functions along with examples and their explanations